
import re
import os

def find_unused_js_files(all_js_files, all_html_files):
    used_js_files = set()
    for html_file in all_html_files:
        try:
            with open(html_file, 'r', encoding='utf-8') as f:
                content = f.read()
                # Find all src attributes in script tags
                matches = re.findall(r'src="([^"]+\.js)"', content)
                for match in matches:
                    # Resolve the absolute path
                    js_file_path = os.path.abspath(os.path.join(os.path.dirname(html_file), match))
                    used_js_files.add(js_file_path)
        except FileNotFoundError:
            print(f"File not found: {html_file}")
        except Exception as e:
            print(f"Error reading file {html_file}: {e}")

    all_js_files_set = set(all_js_files)
    unused_js_files = all_js_files_set - used_js_files

    # Normalize paths for comparison
    normalized_unused_js = set()
    for f in unused_js_files:
        normalized_unused_js.add(os.path.abspath(f))

    # Second pass to handle relative paths from root
    for html_file in all_html_files:
        try:
            with open(html_file, 'r', encoding='utf-8') as f:
                content = f.read()
                matches = re.findall(r'src="([^"]+\.js)"', content)
                for match in matches:
                    if match.startswith('/'):
                        js_file_path = os.path.abspath(os.path.join(os.path.dirname(html_file), '..', match.lstrip('/')))
                        if js_file_path in all_js_files_set:
                             used_js_files.add(js_file_path)
        except Exception as e:
            print(f"Error in second pass for file {html_file}: {e}")


    all_js_files_set = set(all_js_files)
    unused_js_files = all_js_files_set - used_js_files

    return unused_js_files

if __name__ == '__main__':
    all_js_files = [
    "/Users/admin/Documents/te-kete-ako-clean/public/js/quality-badge-system.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/posthog-analytics.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/signup-teacher.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/teacher-dashboard.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/navigation-loader.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/interactive-literacy/js/script.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/curriculum-interactive.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/glm-graphrag-integration.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/enterprise-bulk-operations.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/agent-graphrag-learner.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/saml-sso-integration.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-recommendations.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/auto-suggestions-widget.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/relationship-quality-analyzer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/filtering-system.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/touch-target-auditor.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/kaitiaki-aronui-consciousness.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/curriculum-tagger.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/supabase-client.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/my-kete.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-pathway-explorer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/deepseek-graphrag-integration.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/shared-agent-coordination.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/indexes.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/teaching-variants-auto-generator.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/framer-cultural-gestures-ultimate.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/smart-recommendations.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/sidebar-graphrag-connector.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/related-resources.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/because-you-viewed.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/youtube-api.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/teacher-dashboard-enhanced.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/signup-student.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/ai-recommendations.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/global-search.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/reality-audit-system.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-auto-healer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/smart-recommendation-engine.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/components.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/login.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/kamar-integration.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/te-kete-professional.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/mobile-performance-optimizer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/main.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/enhanced-search.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/progress-tracker.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/adaptive-pathway-generator.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/cultural-intelligence-layer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/supabase-auth.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/cross-subject-discovery-engine.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/mobile-validation-suite.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/component-loader.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/content-recommendation-engine.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/stripe-payments.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/supabase.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/auth-unified.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/content-hierarchy-auto.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/error-monitoring.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/teacher-dashboard-ai.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/master-intelligence-hub.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/games-hub.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/search-live.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-performance-monitor.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/intelligence-integration.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/lazy-loading-optimizer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-connection-counter.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-self-evolution-engine.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/beautiful-font-loader.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-optimizer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/performance-cache-manager.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/oauth-config.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/student-dashboard.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/teaching-variants-synthesizer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/enhanced-graphrag-search.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/env-config.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/legacy-pattern-analyzer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/my-kete-database.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/global-error-handler.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/maori-dictionary-api.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/teaching-variant-generator.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/enhanced-header.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/student-dashboard-enhanced.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/analytics-tracker.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/sw.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/service-worker.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/cross-subject-discovery-improved.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/supabase-singleton.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/config.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/activate-ai-systems.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/adaptive-difficulty-system.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/advanced-analytics.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/advanced-search.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/advanced-youtube-search.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/agent-coordinator.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/ai-teaching-assistant.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/analytics-dashboard.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/animated-stats.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/animations-enhanced.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/assessment-tools.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/breadcrumbs-universal.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/breadcrumbs.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/content-hierarchy.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/counter-animation.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/css-safeguard.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/cultural-components.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/cultural-tooltips.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/curriculum-browser.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/digital-purakau.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/enhanced-footer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/footer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/framer-motion-interactions.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/gamification-system.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-config.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/graphrag-live-stats.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/header-dropdowns.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/homepage.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/learning-analytics.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/loading-toast-system.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/micro-interactions.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/mobile-revolution.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/professional-audit-dashboard.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/professional-enhancements.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/pwa-registration.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/shared-components.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/spelling-bee-game.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/subject-canonical-mapping.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/tukutuku-pattern-generator.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/universal-beauty-enhancer.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/ux-enhancements.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/js/ux-professional.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/tailwind.config.ultimate.js",
    "/Users/admin/Documents/te-kete-ako-clean/public/vendor/supabase.min.js"
]
    all_html_files = [
    "/Users/admin/Documents/te-kete-ako-clean/public/science-hub.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/emergency-lessons.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/assessments-hub.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/cache-test.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/emergency-diagnostic.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/generated-resources-alpha/lessons/ai-ethics-through-māori-data-sovereignty-FIXED.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/generated-resources-alpha/handouts/algebraic-thinking-in-traditional-māori-games.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/toolkit.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/game-development-with-cultural-themes.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/walker-lesson-1.5-reclaiming-the-narrative.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/maori-political-action.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/search.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/index-new.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/interactive-writing-games.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/peel-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/suspense-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/cognitive-writing-strategies.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/english.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/treaty-two-texts.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/writers-toolkit-assessment-rubric.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/lesson-14-digital-korowai.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/decolonization-today.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/social-studies.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/writers-toolkit-progress-tracker.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/digital-writing-tools.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/english/offline.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/advanced-critical-thinking-decision-making.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/society-design-collaboration-framework.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/tools.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/unit-2-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/dashboard.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/social studies/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/resource-discovery-hub.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lessons.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/project-brief.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/virtual-marae.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-5-restoration-kaitiakitanga.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/interactive-learning-demo.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-1-introduction-statistical-investigations.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-6.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-3-building-with-algebra.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-8-art-of-the-upstander.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/educational-transformation-showcase.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/site-map.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/my-kete.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/climate-change-through-te-taiao-māori-lens.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/curriculum-social-sciences.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-5-lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/rhetorical-devices-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/systems-lesson-1-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-1-patterns-and-sequences.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-7-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/sitemap-enhanced.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/index-premium.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-4-balancing-act.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-3-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-5-final-project-presentation.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/te-ao-maori.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-6-presentations.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-6-guardians-future.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/social-sciences-progression-framework.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/curriculum-alignment.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/digital-purakau.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-6-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/whakairo-geometry-lesson.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-1-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/curriculum-english.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/teacher-dashboard.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/writers-toolkit-rhetorical-devices-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/fluency-suspense-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/english-literacy-progression-framework.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-10-data-as-taonga.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-4-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-2-the-mystery-of-x.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/curriculum-index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/youtube.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/cognitive-biases-comprehension-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-3-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-7-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-3-census-population-trends.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/systems-lesson-2-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/teacher-guide.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/subjects.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/project-submission.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-2-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/youtube-library.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-7-tukutuku-transformations.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/curriculum-mathematics.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-3-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-3-field-study-rangahau-taiao.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-4-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/student-dashboard.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/kaitiaki-generated-maori-migration-lesson.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-4-human-impact-conservation.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/privacy-policy.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-9-misinformation-effect.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/other-resources.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/unit-3-lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/resource-connections.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/kaitiaki-aronui-capability-showcase.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-2-analysing-nz-sports-data.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-4-probability-real-world-predictions.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/my-submissions.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/living-whakapapa.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/graphrag-search.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/curriculum-science.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/teacher-dashboard-ai.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-5-the-two-step-shuffle.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/activities.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lighthouse-report.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/lesson-2-biodiversity-endemism.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/diction-tone-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/mathematics/admin-youtube-library.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-show-dont-tell-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/show-dont-tell-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-2-lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-15-digital-rangatiratanga.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-11-the-ripple-effect.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-5-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-1-lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-12-digital-tikanga.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-6-lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/who-has-the-real-power-interactive.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/frayer-model-system.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/system-sorting-cards.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-5-culture-integration.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-inform-structure-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/treaty-articles.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-fluency-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-3-human-impacts.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/digital-storytelling-with-pūrākau-framework.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-6-lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-2-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-1-lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/adaptive-pathways.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-2-lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/conclusion-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/systems-lesson-5-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-5-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-2-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/government-station-cards.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-1-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/traditional-navigation-and-modern-gps-integration.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/indigenous-governance-principles.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/analogy-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-3-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-suspense-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-6-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/suspense-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/worksheet-treaty-of-waitangi-podcast.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-hook-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/gallery-walk-statements.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-2-lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-conclusion-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-5-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/diction-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-4-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/walker-lesson-1.1-who-was-ranginui-walker.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-tone-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-4-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-what-is-our-digital-whenua.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-5-science-of-screen-time.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-analogy-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/ai-ethics-through-māori-data-sovereignty-FIXED.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/skate-park-campaign.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-13-reclaiming-your-mauri.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-7-words-as-taonga.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/colonization-timeline.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-2-the-great-migration.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-5-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-4-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/brain-break-wordsearch-lesson.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/maori-governance-systems.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-3-government-systems.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-2-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/career-pathways-in-stem-for-māori-students.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-3-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-6-lesson-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-7-lesson-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-3.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-treaty-of-waitangi.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/fluency-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-2-1.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-6-designing-for-well-being.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/tone-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-diction-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/living-tiriti-examples.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-4-lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-2-group-formation.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-4-rights-economy.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/indigenous-systems-examples.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-1-who-was-ranginui-walker.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/hook-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-revision-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/inform-structure-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/revision-lesson-plan.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-4-body-as-sensor.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-3-lesson-4.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/indigenous-feedback-framework.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/unit-4-lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-1-society-exploration.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-18-digital-showcase.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-5-2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/lesson-17-creation-workshop.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/science/writers-toolkit-implementation-guide.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/general/navigation_fix_standard_header.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/technology/navigation_fix_standard_header.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/technology/resource-hub.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/technology/register.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/technology/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/unit-5-lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lessons.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/project-brief.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/virtual-marae.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-1-what-is-an-ecosystem.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/curriculum-languages.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/energy-sustainability-lesson.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/experiences.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/show-and-tell-activities.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/indigenous-learning-systems.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/source-evaluation-matrix.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/evidence-evaluation-frameworks.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/my-kete.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-7.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/rnz-analysis-framework.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/curriculum-health-pe.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/auth-diagnostics.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/adaptive-pathways.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/classroom-leaderboard.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/critical-thinking-toolkit.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/curriculum-technology.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/environmental-text-analysis-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/engineering-design-lesson.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-sustainable-technology.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/political-cartoon-analysis-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-1-kaitiakitanga-intro.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/arguments-of-tino-rangatiratanga-handout.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-2-food-webs.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/reset-password.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/curriculum-v2.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-3-blueprint-for-a-healthy-whare.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/platforms.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/contact.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-8.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/curriculum-arts.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/about.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-16-project-launch.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/forgot-password.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-design-thinking.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-10.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/learning-pathways.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/ai-ethics-through-māori-data-sovereignty.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/index.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/ai-hub.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-5.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/activities.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-9.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/emergency-diagnostic.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/te reo māori/lesson-2-four-walls.html",
    "/Users/admin/Documents/te-kete-ako-clean/public/integrated-lessons/index.html"
]
    unused_files = find_unused_js_files(all_js_files, all_html_files)
    for file in unused_files:
        print(file)
