[build]
  command = "./copy-files.sh && echo 'BUILD TIMESTAMP:' $(date)"
  publish = "public"

[[redirects]]
  from = "/curriculum"
  to = "/curriculum-alignment.html"
  status = 301

[[redirects]]
  from = "/maori-wordle"
  to = "/games/te-reo-wordle.html"
  status = 301

[[redirects]]
  from = "/activities"
  to = "/activities.html"
  status = 301

[[redirects]]
  from = "/subjects"
  to = "/subjects.html"
  status = 200

[[redirects]]  
  from = "/unit-plans"
  to = "/unit-plans.html"
  status = 200

[[redirects]]
  from = "/lessons" 
  to = "/lessons.html"
  status = 200

[[redirects]]
  from = "/handouts"
  to = "/handouts.html" 
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
