[build]
  publish = "."

[[redirects]]
  from = "/curriculum"
  to = "/curriculum-alignment.html"
  status = 301

[[redirects]]
  from = "/maori-wordle"
  to = "/games/te-reo-wordle.html"
  status = 301

[[redirects]]
  from = "/activities"
  to = "/activities.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"
