[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard for security)
# STRIPE_SECRET_KEY=sk_test_...
# STRIPE_PUBLISHABLE_KEY=pk_test_...
# POSTHOG_API_KEY=phc_...
# ANTHROPIC_API_KEY=sk-ant-...

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - only for routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
