[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/curriculum"
  to = "/curriculum-alignment.html"
  status = 301

[[redirects]]
  from = "/maori-wordle"
  to = "/games/te-reo-wordle.html"
  status = 301

[[redirects]]
  from = "/activities"
  to = "/activities.html"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Allow direct access to these specific pages
[[redirects]]
  from = "/handouts.html"
  to = "/handouts.html"
  status = 200

[[redirects]]
  from = "/youtube.html"
  to = "/youtube.html"
  status = 200

[[redirects]]
  from = "/lessons.html"
  to = "/lessons.html"
  status = 200

[[redirects]]
  from = "/resource-hub.html"
  to = "/resource-hub.html"
  status = 200

[[redirects]]
  from = "/curriculum-index.html"
  to = "/curriculum-index.html"
  status = 200

[[redirects]]
  from = "/teachers/index.html"
  to = "/teachers/index.html"
  status = 200

[[redirects]]
  from = "/games.html"
  to = "/games.html"
  status = 200

[[redirects]]
  from = "/guided-inquiry-unit/*"
  to = "/guided-inquiry-unit/:splat"
  status = 200

[[redirects]]
  from = "/units/*"
  to = "/units/:splat"
  status = 200

[[redirects]]
  from = "/lessons/*"
  to = "/lessons/:splat"
  status = 200

[[redirects]]
  from = "/handouts/*"
  to = "/handouts/:splat"
  status = 200

[[redirects]]
  from = "/404/*"
  to = "/index.html"
  status = 200

# SPA fallback - only applies to routes without matching files
# Static files in /handouts/*, /units/*, /lessons/*, etc. are served directly
# This redirect has lowest priority and only triggers for 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Build hooks for validation and testing
[build.lifecycle]
  onInit = "echo 'Starting build process...'"
  onDev = "echo 'Development mode'"
  preBuild = "npm run predeploy"
  onBuild = "echo 'Building...'"
  onSuccess = "echo 'Build successful!'"
  onFailure = "echo 'Build failed!'"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://nlgldaqtubrlcqddppbq.supabase.co https://api.exa.ai https://api.deepseek.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; worker-src 'self'; child-src 'none'; upgrade-insecure-requests; block-all-mixed-content;"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
