-- Populate NZ Schools Database
-- Comprehensive list of NZ secondary and intermediate schools by region

INSERT INTO nz_schools (name, location, region, school_type, authority, decile) VALUES

-- NORTHLAND
('Whangarei Boys High School', 'Whangarei', 'Northland', 'Secondary', 'State', 6),
('Whangarei Girls High School', 'Whangarei', 'Northland', 'Secondary', 'State', 5),
('Kamo High School', 'Whangarei', 'Northland', 'Secondary', 'State', 4),
('Kerikeri High School', 'Kerikeri', 'Northland', 'Secondary', 'State', 7),
('Bay of Islands College', 'Kawakawa', 'Northland', 'Secondary', 'State', 3),
('Dargaville High School', 'Dargaville', 'Northland', 'Secondary', 'State', 3),
('Kaitaia College', 'Kaitaia', 'Northland', 'Secondary', 'State', 2),

-- AUCKLAND
('Auck land Grammar School', 'Auckland Central', 'Auckland', 'Secondary', 'State', 10),
('Mount Albert Grammar School', 'Mount Albert', 'Auckland', 'Secondary', 'State', 10),
('Western Springs College', 'Western Springs', 'Auckland', 'Secondary', 'State', 7),
('Epsom Girls Grammar School', 'Epsom', 'Auckland', 'Secondary', 'State', 10),
('Auckland Girls Grammar School', 'Freemans Bay', 'Auckland', 'Secondary', 'State', 10),
('Takapuna Grammar School', 'Takapuna', 'Auckland', 'Secondary', 'State', 10),
('Rangitoto College', 'Mairangi Bay', 'Auckland', 'Secondary', 'State', 10),
('Long Bay College', 'Long Bay', 'Auckland', 'Secondary', 'State', 9),
('Westlake Boys High School', 'Takapuna', 'Auckland', 'Secondary', 'State', 10),
('Westlake Girls High School', 'Takapuna', 'Auckland', 'Secondary', 'State', 10),
('Glendowie College', 'Glendowie', 'Auckland', 'Secondary', 'State', 10),
('Macleans College', 'Bucklands Beach', 'Auckland', 'Secondary', 'State', 10),
('Howick College', 'Howick', 'Auckland', 'Secondary', 'State', 9),
('Pakuranga College', 'Pakuranga', 'Auckland', 'Secondary', 'State', 9),
('Botany Downs Secondary College', 'Botany Downs', 'Auckland', 'Secondary', 'State', 10),
('Sancta Maria College', 'Flat Bush', 'Auckland', 'Secondary', 'State Integrated', 5),
('Manurewa High School', 'Manurewa', 'Auckland', 'Secondary', 'State', 2),
('James Cook High School', 'Manurewa', 'Auckland', 'Secondary', 'State', 2),
('Tangaroa College', 'Otara', 'Auckland', 'Secondary', 'State', 1),
('Sir Edmund Hillary Collegiate', 'Otara', 'Auckland', 'Secondary', 'State', 1),
('Otahuhu College', 'Otahuhu', 'Auckland', 'Secondary', 'State', 2),
('One Tree Hill College', 'One Tree Hill', 'Auckland', 'Secondary', 'State', 4),
('Mount Roskill Grammar School', 'Mount Roskill', 'Auckland', 'Secondary', 'State', 4),
('Avondale College', 'Avondale', 'Auckland', 'Secondary', 'State', 4),
('Kelston Boys High School', 'Kelston', 'Auckland', 'Secondary', 'State', 3),
('Kelston Girls College', 'Kelston', 'Auckland', 'Secondary', 'State', 3),
('Henderson High School', 'Henderson', 'Auckland', 'Secondary', 'State', 3),
('Rutherford College', 'Te Atatu Peninsula', 'Auckland', 'Secondary', 'State', 5),
('Waitakere College', 'Henderson', 'Auckland', 'Secondary', 'State', 3),
('Massey High School', 'Massey', 'Auckland', 'Secondary', 'State', 6),
('Albany Senior High School', 'Albany', 'Auckland', 'Secondary', 'State', 10),
('Birkenhead College', 'Birkenhead', 'Auckland', 'Secondary', 'State', 7),
('Northcote College', 'Northcote', 'Auckland', 'Secondary', 'State', 7),
('Rosmini College', 'Takapuna', 'Auckland', 'Secondary', 'State Integrated', 9),
('Carmel College', 'Milford', 'Auckland', 'Secondary', 'State Integrated', 9),
('Diocesan School for Girls', 'Epsom', 'Auckland', 'Secondary', 'Private', 10),
('Kings College', 'Otahuhu', 'Auckland', 'Secondary', 'Private', 10),
('St Kentigern College', 'Pakuranga', 'Auckland', 'Secondary', 'Private', 10),
('ACG Parnell College', 'Parnell', 'Auckland', 'Secondary', 'Private', 10),
('Baradene College', 'Remuera', 'Auckland', 'Secondary', 'State Integrated', 10),
('St Peters College', 'Grafton', 'Auckland', 'Secondary', 'State Integrated', 8),
('Sacred Heart College', 'Glendowie', 'Auckland', 'Secondary', 'State Integrated', 9),
('Lynfield College', 'Lynfield', 'Auckland', 'Secondary', 'State', 7),
('Green Bay High School', 'Green Bay', 'Auckland', 'Secondary', 'State', 5),
('De La Salle College', 'Mangere East', 'Auckland', 'Secondary', 'State Integrated', 3),
('Marcellin College', 'Royal Oak', 'Auckland', 'Secondary', 'State Integrated', 6),

-- WAIKATO
('Hamilton Boys High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 8),
('Hamilton Girls High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 8),
('Hillcrest High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 8),
('Fraser High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 6),
('Fairfield College', 'Hamilton', 'Waikato', 'Secondary', 'State', 4),
('Melville High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 7),
('Sacred Heart Girls College Hamilton', 'Hamilton', 'Waikato', 'Secondary', 'State Integrated', 7),
('St Johns College Hamilton', 'Hamilton', 'Waikato', 'Secondary', 'State Integrated', 6),
('Cambridge High School', 'Cambridge', 'Waikato', 'Secondary', 'State', 8),
('Te Awamutu College', 'Te Awamutu', 'Waikato', 'Secondary', 'State', 6),
('Matamata College', 'Matamata', 'Waikato', 'Secondary', 'State', 6),
('Morrinsville College', 'Morrinsville', 'Waikato', 'Secondary', 'State', 7),
('Thames High School', 'Thames', 'Waikato', 'Secondary', 'State', 5),
('Tokoroa High School', 'Tokoroa', 'Waikato', 'Secondary', 'State', 2),
('Putaruru College', 'Putaruru', 'Waikato', 'Secondary', 'State', 3),

-- BAY OF PLENTY
('Tauranga Boys College', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State', 8),
('Tauranga Girls College', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State', 7),
('Mount Maunganui College', 'Mount Maunganui', 'Bay of Plenty', 'Secondary', 'State', 8),
('Otumoetai College', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State', 9),
('Aquinas College Tauranga', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State Integrated', 8),
('Bethlehem College', 'Bethlehem', 'Bay of Plenty', 'Secondary', 'Private', 9),
('Rotorua Boys High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 5),
('Rotorua Girls High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 5),
('Western Heights High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 3),
('Rotorua Lakes High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 4),
('John Paul College Rotorua', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State Integrated', 6),
('Whakatane High School', 'Whakatane', 'Bay of Plenty', 'Secondary', 'State', 5),
('Trident High School', 'Whakatane', 'Bay of Plenty', 'Secondary', 'State', 4),
('Edgecumbe College', 'Edgecumbe', 'Bay of Plenty', 'Secondary', 'State', 3),
('Opotiki College', 'Opotiki', 'Bay of Plenty', 'Secondary', 'State', 2),
('Te Puke High School', 'Te Puke', 'Bay of Plenty', 'Secondary', 'State', 4),
('Katikati College', 'Katikati', 'Bay of Plenty', 'Secondary', 'State', 6),

-- GISBORNE
('Gisborne Boys High School', 'Gisborne', 'Gisborne', 'Secondary', 'State', 4),
('Gisborne Girls High School', 'Gisborne', 'Gisborne', 'Secondary', 'State', 4),
('Lytton High School', 'Gisborne', 'Gisborne', 'Secondary', 'State', 2),
('Campion College', 'Gisborne', 'Gisborne', 'Secondary', 'State Integrated', 4),

-- HAWKE'S BAY
('Napier Boys High School', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 7),
('Napier Girls High School', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 7),
('Tamatea High School', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 4),
('William Colenso College', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 5),
('Hastings Boys High School', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 6),
('Hastings Girls High School', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 6),
('Karamu High School', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 5),
('Flaxmere College', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 1),
('Lindisfarne College', 'Hastings', 'Hawke''s Bay', 'Secondary', 'Private', 8),
('Iona College', 'Havelock North', 'Hawke''s Bay', 'Secondary', 'State Integrated', 8),
('Havelock North High School', 'Havelock North', 'Hawke''s Bay', 'Secondary', 'State', 9),
('Central Hawke''s Bay College', 'Waipukurau', 'Hawke''s Bay', 'Secondary', 'State', 5),
('Dannevirke High School', 'Dannevirke', 'Hawke''s Bay', 'Secondary', 'State', 4),

-- TARANAKI
('New Plymouth Boys High School', 'New Plymouth', 'Taranaki', 'Secondary', 'State', 8),
('New Plymouth Girls High School', 'New Plymouth', 'Taranaki', 'Secondary', 'State', 8),
('Spotswood College', 'New Plymouth', 'Taranaki', 'Secondary', 'State', 6),
('Francis Douglas Memorial College', 'New Plymouth', 'Taranaki', 'Secondary', 'State Integrated', 7),
('Sacred Heart Girls College New Plymouth', 'New Plymouth', 'Taranaki', 'Secondary', 'State Integrated', 7),
('Inglewood High School', 'Inglewood', 'Taranaki', 'Secondary', 'State', 5),
('Stratford High School', 'Stratford', 'Taranaki', 'Secondary', 'State', 6),
('Hawera High School', 'Hawera', 'Taranaki', 'Secondary', 'State', 4),
('Opunake High School', 'Opunake', 'Taranaki', 'Secondary', 'State', 4),

-- MANAWATŪ-WHANGANUI
('Palmerston North Boys High School', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 8),
('Palmerston North Girls High School', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 8),
('Freyberg High School', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 6),
('Awatapu College', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 7),
('Longburn Adventist College', 'Longburn', 'Manawatū-Whanganui', 'Secondary', 'Private', 7),
('Feilding High School', 'Feilding', 'Manawatū-Whanganui', 'Secondary', 'State', 7),
('Whanganui High School', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'State', 5),
('Whanganui City College', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'State', 3),
('Whanganui Collegiate School', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'Private', 8),
('Cullinane College', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'State Integrated', 5),
('Taihape Area School', 'Taihape', 'Manawatū-Whanganui', 'Area School', 'State', 3),
('Ruapehu College', 'Ohakune', 'Manawatū-Whanganui', 'Secondary', 'State', 3),

-- WELLINGTON
('Wellington College', 'Wellington', 'Wellington', 'Secondary', 'State', 10),
('Wellington Girls College', 'Wellington', 'Wellington', 'Secondary', 'State', 9),
('Wellington High School', 'Wellington', 'Wellington', 'Secondary', 'State', 7),
('Onslow College', 'Johnsonville', 'Wellington', 'Secondary', 'State', 8),
('Wellington East Girls College', 'Mount Victoria', 'Wellington', 'Secondary', 'State', 7),
('Scots College', 'Strathmore', 'Wellington', 'Secondary', 'Private', 10),
('Queen Margaret College', 'Thorndon', 'Wellington', 'Secondary', 'Private', 10),
('Samuel Marsden Collegiate School', 'Karori', 'Wellington', 'Secondary', 'Private', 10),
('St Patricks College Wellington', 'Kilbirnie', 'Wellington', 'Secondary', 'State Integrated', 8),
('St Marys College Wellington', 'Wellington', 'Wellington', 'Secondary', 'State Integrated', 8),
('St Catherines College Wellington', 'Kilbirnie', 'Wellington', 'Secondary', 'State Integrated', 9),
('Hutt Valley High School', 'Lower Hutt', 'Wellington', 'Secondary', 'State', 5),
('Naenae College', 'Lower Hutt', 'Wellington', 'Secondary', 'State', 2),
('Taita College', 'Lower Hutt', 'Wellington', 'Secondary', 'State', 3),
('Wainuiomata High School', 'Wainuiomata', 'Wellington', 'Secondary', 'State', 2),
('Heretaunga College', 'Upper Hutt', 'Wellington', 'Secondary', 'State', 5),
('Upper Hutt College', 'Upper Hutt', 'Wellington', 'Secondary', 'State', 6),
('St Bernards College', 'Lower Hutt', 'Wellington', 'Secondary', 'State Integrated', 6),
('Sacred Heart College Lower Hutt', 'Lower Hutt', 'Wellington', 'Secondary', 'State Integrated', 6),
('St Oran''s College', 'Lower Hutt', 'Wellington', 'Secondary', 'State Integrated', 5),
('Paraparaumu College', 'Paraparaumu', 'Wellington', 'Secondary', 'State', 7),
('Kapiti College', 'Raumati Beach', 'Wellington', 'Secondary', 'State', 6),
('Otaki College', 'Otaki', 'Wellington', 'Secondary', 'State', 4),
('Porirua College', 'Porirua', 'Wellington', 'Secondary', 'State', 2),
('Aotea College', 'Porirua', 'Wellington', 'Secondary', 'State', 4),
('Mana College', 'Porirua', 'Wellington', 'Secondary', 'State', 3),
('Tawa College', 'Tawa', 'Wellington', 'Secondary', 'State', 8),
('Bishop Viard College', 'Porirua', 'Wellington', 'Secondary', 'State Integrated', 5),

-- TASMAN
('Waimea College', 'Richmond', 'Tasman', 'Secondary', 'State', 7),
('Motueka High School', 'Motueka', 'Tasman', 'Secondary', 'State', 5),
('Golden Bay High School', 'Takaka', 'Tasman', 'Secondary', 'State', 6),

-- NELSON
('Nelson College', 'Nelson', 'Nelson', 'Secondary', 'State', 8),
('Nelson College for Girls', 'Nelson', 'Nelson', 'Secondary', 'State', 8),
('Nayland College', 'Stoke', 'Nelson', 'Secondary', 'State', 7),
('Garin College', 'Richmond', 'Nelson', 'Secondary', 'State Integrated', 7),

-- MARLBOROUGH
('Marlborough Boys College', 'Blenheim', 'Marlborough', 'Secondary', 'State', 7),
('Marlborough Girls College', 'Blenheim', 'Marlborough', 'Secondary', 'State', 7),
('Queen Charlotte College', 'Picton', 'Marlborough', 'Secondary', 'State', 6),

-- WEST COAST
('Greymouth High School', 'Greymouth', 'West Coast', 'Secondary', 'State', 5),
('Westland High School', 'Hokitika', 'West Coast', 'Secondary', 'State', 4),
('Buller High School', 'Westport', 'West Coast', 'Secondary', 'State', 4),

-- CANTERBURY
('Christchurch Boys High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 9),
('Christchurch Girls High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 9),
('Burnside High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 9),
('Riccarton High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 6),
('Avonside Girls High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 7),
('Shirley Boys High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 6),
('Papanui High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 7),
('Hillmorton High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 5),
('Cashmere High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 9),
('Lincoln High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 8),
('Hornby High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 4),
('Halswell School', 'Christchurch', 'Canterbury', 'Composite', 'State', 6),
('Villa Maria College', 'Christchurch', 'Canterbury', 'Secondary', 'State Integrated', 8),
('Marian College', 'Christchurch', 'Canterbury', 'Secondary', 'State Integrated', 7),
('St Bedes College', 'Christchurch', 'Canterbury', 'Secondary', 'State Integrated', 9),
('St Thomas of Canterbury College', 'Christchurch', 'Canterbury', 'Secondary', 'State Integrated', 8),
('Catholic Cathedral College', 'Christchurch', 'Canterbury', 'Secondary', 'State Integrated', 6),
('Mairehau High School', 'Christchurch', 'Canterbury', 'Secondary', 'State', 5),
('Rangiora High School', 'Rangiora', 'Canterbury', 'Secondary', 'State', 7),
('Kaiapoi High School', 'Kaiapoi', 'Canterbury', 'Secondary', 'State', 7),
('Ashburton College', 'Ashburton', 'Canterbury', 'Secondary', 'State', 6),
('Mount Hutt College', 'Methven', 'Canterbury', 'Secondary', 'State', 6),
('Timaru Boys High School', 'Timaru', 'Canterbury', 'Secondary', 'State', 7),
('Timaru Girls High School', 'Timaru', 'Canterbury', 'Secondary', 'State', 7),
('Roncalli College', 'Timaru', 'Canterbury', 'Secondary', 'State Integrated', 6),
('Mountainview High School', 'Timaru', 'Canterbury', 'Secondary', 'State', 4),
('Waimate High School', 'Waimate', 'Canterbury', 'Secondary', 'State', 5),
('Geraldine High School', 'Geraldine', 'Canterbury', 'Secondary', 'State', 7),

-- OTAGO
('Otago Boys High School', 'Dunedin', 'Otago', 'Secondary', 'State', 8),
('Otago Girls High School', 'Dunedin', 'Otago', 'Secondary', 'State', 8),
('Kings High School', 'Dunedin', 'Otago', 'Secondary', 'State', 7),
('Queens High School', 'Dunedin', 'Otago', 'Secondary', 'State', 7),
('Bayfield High School', 'Dunedin', 'Otago', 'Secondary', 'State', 6),
('Kaikorai Valley College', 'Dunedin', 'Otago', 'Secondary', 'State', 5),
('Logan Park High School', 'Dunedin', 'Otago', 'Secondary', 'State', 6),
('Kavanagh College', 'Dunedin', 'Otago', 'Secondary', 'State Integrated', 7),
('St Hildas Collegiate', 'Dunedin', 'Otago', 'Secondary', 'Private', 9),
('John McGlashan College', 'Dunedin', 'Otago', 'Secondary', 'State Integrated', 8),
('Columba College', 'Dunedin', 'Otago', 'Secondary', 'Private', 9),
('Taieri College', 'Mosgiel', 'Otago', 'Secondary', 'State', 7),
('Dunstan High School', 'Alexandra', 'Otago', 'Secondary', 'State', 6),
('Mount Aspiring College', 'Wanaka', 'Otago', 'Secondary', 'State', 9),
('Wakatipu High School', 'Queenstown', 'Otago', 'Secondary', 'State', 9),

-- SOUTHLAND
('Southland Boys High School', 'Invercargill', 'Southland', 'Secondary', 'State', 7),
('Southland Girls High School', 'Invercargill', 'Southland', 'Secondary', 'State', 7),
('James Hargest College', 'Invercargill', 'Southland', 'Secondary', 'State', 7),
('Verdon College', 'Invercargill', 'Southland', 'Secondary', 'State Integrated', 6),
('St Peters College Southland', 'Gore', 'Southland', 'Secondary', 'State Integrated', 5),
('Gore High School', 'Gore', 'Southland', 'Secondary', 'State', 5),
('Menzies College', 'Wyndham', 'Southland', 'Secondary', 'State', 4),
('Central Southland College', 'Winton', 'Southland', 'Secondary', 'State', 5),
('Fiordland College', 'Te Anau', 'Southland', 'Secondary', 'State', 6),

-- INTERMEDIATE SCHOOLS (Major Ones)
('Intermediate Normal School Wellington', 'Wellington', 'Wellington', 'Intermediate', 'State', 10),
('Tawa Intermediate', 'Tawa', 'Wellington', 'Intermediate', 'State', 8),
('Karori Normal School', 'Karori', 'Wellington', 'Intermediate', 'State', 10),
('Naenae Intermediate', 'Lower Hutt', 'Wellington', 'Intermediate', 'State', 2),
('Fraser Avenue School', 'Hamilton', 'Waikato', 'Intermediate', 'State', 7),
('Berkley Normal Middle School', 'Hamilton', 'Waikato', 'Intermediate', 'State', 8),
('Cambridge Middle School', 'Cambridge', 'Waikato', 'Intermediate', 'State', 8),
('Intermediate', 'Auckland', 'Auckland', 'Intermediate', 'State', 10),
('Northcross Intermediate', 'Auckland', 'Auckland', 'Intermediate', 'State', 10),
('Bayswater School', 'Auckland', 'Auckland', 'Intermediate', 'State', 10),
('Takapuna Normal Intermediate', 'Takapuna', 'Auckland', 'Intermediate', 'State', 10),
('Stanley Bay School', 'Devonport', 'Auckland', 'Intermediate', 'State', 10),
('Belmont Intermediate', 'Belmont', 'Auckland', 'Intermediate', 'State', 10),
('Long Bay Primary', 'Long Bay', 'Auckland', 'Intermediate', 'State', 10),
('Albany Junior High School', 'Albany', 'Auckland', 'Intermediate', 'State', 10),
('Glenfield Intermediate', 'Glenfield', 'Auckland', 'Intermediate', 'State', 7),
('Birkenhead Primary', 'Birkenhead', 'Auckland', 'Intermediate', 'State', 8),
('Bayfield School', 'Auckland', 'Auckland', 'Intermediate', 'State', 9),
('Pakuranga Intermediate', 'Pakuranga', 'Auckland', 'Intermediate', 'State', 9),
('Howick Intermediate', 'Howick', 'Auckland', 'Intermediate', 'State', 10),
('Somerville Intermediate', 'Howick', 'Auckland', 'Intermediate', 'State', 10),
('Cockle Bay School', 'Howick', 'Auckland', 'Intermediate', 'State', 10),
('Bucklands Beach Intermediate', 'Bucklands Beach', 'Auckland', 'Intermediate', 'State', 10),
('Farm Cove Intermediate', 'Farm Cove', 'Auckland', 'Intermediate', 'State', 10),
('Remuera Intermediate', 'Remuera', 'Auckland', 'Intermediate', 'State', 10),
('Meadowbank School', 'Meadowbank', 'Auckland', 'Intermediate', 'State', 10),
('Glendowie School', 'Glendowie', 'Auckland', 'Intermediate', 'State', 10),
('Selwyn College', 'Kohimarama', 'Auckland', 'Secondary', 'State', 9),
('Tamaki College', 'Glen Innes', 'Auckland', 'Secondary', 'State', 2),
('St Pauls College Auckland', 'Ponsonby', 'Auckland', 'Secondary', 'State Integrated', 9),
('Auckland Normal Intermediate', 'Mount Eden', 'Auckland', 'Intermediate', 'State', 9),
('Epsom Normal Primary', 'Epsom', 'Auckland', 'Intermediate', 'State', 10),
('Balmoral School', 'Auckland', 'Auckland', 'Intermediate', 'State', 9),
('Mount Roskill Intermediate', 'Mount Roskill', 'Auckland', 'Intermediate', 'State', 4),
('Wesley Intermediate', 'Mount Roskill', 'Auckland', 'Intermediate', 'State', 5),
('Royal Oak Intermediate', 'Royal Oak', 'Auckland', 'Intermediate', 'State', 6),
('Elm Park School', 'Manurewa', 'Auckland', 'Intermediate', 'State', 2),
('Redoubt North School', 'Manukau', 'Auckland', 'Intermediate', 'State', 3),
('Flat Bush School', 'Flat Bush', 'Auckland', 'Intermediate', 'State', 4),
('Whitford School', 'Whitford', 'Auckland', 'Intermediate', 'State', 10),
('Pukekohe Intermediate', 'Pukekohe', 'Auckland', 'Intermediate', 'State', 5),
('Papakura Intermediate', 'Papakura', 'Auckland', 'Intermediate', 'State', 4),

-- KURA MĀORI (Māori-medium schools)
('Te Kura Kaupapa Māori o Te Koutu', 'Rotorua', 'Bay of Plenty', 'Composite', 'State', 1),
('Te Kura Kaupapa Māori o Hoani Waititi', 'West Auckland', 'Auckland', 'Composite', 'State', 3),
('Te Kura Kaupapa Māori o Nga Maungarongo', 'Whangarei', 'Northland', 'Composite', 'State', 2),
('Te Wharekura o Rakaumangamanga', 'Huntly', 'Waikato', 'Secondary', 'State', 2),
('Te Wharekura o Mauao', 'Mount Maunganui', 'Bay of Plenty', 'Secondary', 'State', 4),
('Te Kura Kaupapa Māori o Te Whanau Tahi', 'Hastings', 'Hawke''s Bay', 'Composite', 'State', 2),
('Kia Aroha College', 'Wellington', 'Wellington', 'Secondary', 'State', 3),
('Aorere College', 'Mangere', 'Auckland', 'Secondary', 'State', 2),
('Southern Cross Campus', 'Mangere', 'Auckland', 'Composite', 'State', 1),

-- PRIVATE/INDEPENDENT SCHOOLS
('ACG Strathallan', 'Karaka', 'Auckland', 'Secondary', 'Private', 10),
('ACG Sunderland', 'Pakuranga Heights', 'Auckland', 'Secondary', 'Private', 10),
('Kristin School', 'Albany', 'Auckland', 'Secondary', 'Private', 10),
('Pinehurst School', 'Albany', 'Auckland', 'Secondary', 'Private', 10),
('Rangitoto College', 'Mairangi Bay', 'Auckland', 'Secondary', 'State', 10),
('Mahurangi College', 'Warkworth', 'Auckland', 'Secondary', 'State', 7),
('Rodney College', 'Wellsford', 'Auckland', 'Secondary', 'State', 4),
('Kingsway School', 'Silverdale', 'Auckland', 'Composite', 'Private', 10),
('Elim Christian College', 'Botany', 'Auckland', 'Secondary', 'Private', 8),
('St Dominics College', 'Henderson', 'Auckland', 'Secondary', 'State Integrated', 5),
('Liston College', 'Henderson', 'Auckland', 'Secondary', 'State Integrated', 6),
('St Pauls Collegiate', 'Hamilton', 'Waikato', 'Secondary', 'Private', 9),
('Tauranga Intermediate', 'Tauranga', 'Bay of Plenty', 'Intermediate', 'State', 8),
('Gate Pa School', 'Tauranga', 'Bay of Plenty', 'Intermediate', 'State', 5),

-- ADDITIONAL MAJOR SCHOOLS
('Macleans College', 'Bucklands Beach', 'Auckland', 'Secondary', 'State', 10),
('Whangaparaoa College', 'Whangaparaoa', 'Auckland', 'Secondary', 'State', 9),
('Orewa College', 'Orewa', 'Auckland', 'Secondary', 'State', 8),
('Hutt International Boys School', 'Lower Hutt', 'Wellington', 'Secondary', 'Private', 9),
('Chilton St James School', 'Lower Hutt', 'Wellington', 'Secondary', 'Private', 10),
('St Marys College Auckland', 'Ponsonby', 'Auckland', 'Secondary', 'State Integrated', 9),
('Baradene College', 'Remuera', 'Auckland', 'Secondary', 'State Integrated', 10),
('Carmel College Auckland', 'Milford', 'Auckland', 'Secondary', 'State Integrated', 9),
('Marist College', 'Mount Albert', 'Auckland', 'Secondary', 'State Integrated', 6),
('St Dominics Catholic College', 'Henderson', 'Auckland', 'Secondary', 'State Integrated', 5),
('Sancta Maria College Auckland', 'Flat Bush', 'Auckland', 'Secondary', 'State Integrated', 5),
('McAuley High School', 'Otahuhu', 'Auckland', 'Secondary', 'State Integrated', 3),
('Marcellin College Auckland', 'Royal Oak', 'Auckland', 'Secondary', 'State Integrated', 6),
('St Peters College Auckland', 'Grafton', 'Auckland', 'Secondary', 'State Integrated', 8),
('Edmund Rice College', 'Whakatane', 'Bay of Plenty', 'Secondary', 'State Integrated', 4)

ON CONFLICT (name) DO NOTHING;

