-- NORTHLAND
('Whangarei Boys High School', 'Whangarei', 'Northland', 'Secondary', 'State', 6),
('Whangarei Girls High School', 'Whangarei', 'Northland', 'Secondary', 'State', 5),
('Kamo High School', 'Whangarei', 'Northland', 'Secondary', 'State', 4),
('Kerikeri High School', 'Kerikeri', 'Northland', 'Secondary', 'State', 7),
('Bay of Islands College', 'Kawakawa', 'Northland', 'Secondary', 'State', 3),
('Dargaville High School', 'Dargaville', 'Northland', 'Secondary', 'State', 3),
('Kaitaia College', 'Kaitaia', 'Northland', 'Secondary', 'State', 2),

-- AUCKLAND
('Auck land Grammar School', 'Auckland Central', 'Auckland', 'Secondary', 'State', 10),
('Mount Albert Grammar School', 'Mount Albert', 'Auckland', 'Secondary', 'State', 10),
('Western Springs College', 'Western Springs', 'Auckland', 'Secondary', 'State', 7),
('Epsom Girls Grammar School', 'Epsom', 'Auckland', 'Secondary', 'State', 10),
('Auckland Girls Grammar School', 'Freemans Bay', 'Auckland', 'Secondary', 'State', 10),
('Takapuna Grammar School', 'Takapuna', 'Auckland', 'Secondary', 'State', 10),
('Rangitoto College', 'Mairangi Bay', 'Auckland', 'Secondary', 'State', 10),
('Long Bay College', 'Long Bay', 'Auckland', 'Secondary', 'State', 9),
('Westlake Boys High School', 'Takapuna', 'Auckland', 'Secondary', 'State', 10),
('Westlake Girls High School', 'Takapuna', 'Auckland', 'Secondary', 'State', 10),
('Glendowie College', 'Glendowie', 'Auckland', 'Secondary', 'State', 10),
('Macleans College', 'Bucklands Beach', 'Auckland', 'Secondary', 'State', 10),
('Howick College', 'Howick', 'Auckland', 'Secondary', 'State', 9),
('Pakuranga College', 'Pakuranga', 'Auckland', 'Secondary', 'State', 9),
('Botany Downs Secondary College', 'Botany Downs', 'Auckland', 'Secondary', 'State', 10),
('Sancta Maria College', 'Flat Bush', 'Auckland', 'Secondary', 'State Integrated', 5),
('Manurewa High School', 'Manurewa', 'Auckland', 'Secondary', 'State', 2),
('James Cook High School', 'Manurewa', 'Auckland', 'Secondary', 'State', 2),
('Tangaroa College', 'Otara', 'Auckland', 'Secondary', 'State', 1),
('Sir Edmund Hillary Collegiate', 'Otara', 'Auckland', 'Secondary', 'State', 1),
('Otahuhu College', 'Otahuhu', 'Auckland', 'Secondary', 'State', 2),
('One Tree Hill College', 'One Tree Hill', 'Auckland', 'Secondary', 'State', 4),
('Mount Roskill Grammar School', 'Mount Roskill', 'Auckland', 'Secondary', 'State', 4),
('Avondale College', 'Avondale', 'Auckland', 'Secondary', 'State', 4),
('Kelston Boys High School', 'Kelston', 'Auckland', 'Secondary', 'State', 3),
('Kelston Girls College', 'Kelston', 'Auckland', 'Secondary', 'State', 3),
('Henderson High School', 'Henderson', 'Auckland', 'Secondary', 'State', 3),
('Rutherford College', 'Te Atatu Peninsula', 'Auckland', 'Secondary', 'State', 5),
('Waitakere College', 'Henderson', 'Auckland', 'Secondary', 'State', 3),
('Massey High School', 'Massey', 'Auckland', 'Secondary', 'State', 6),
('Albany Senior High School', 'Albany', 'Auckland', 'Secondary', 'State', 10),
('Birkenhead College', 'Birkenhead', 'Auckland', 'Secondary', 'State', 7),
('Northcote College', 'Northcote', 'Auckland', 'Secondary', 'State', 7),
('Rosmini College', 'Takapuna', 'Auckland', 'Secondary', 'State Integrated', 9),
('Carmel College', 'Milford', 'Auckland', 'Secondary', 'State Integrated', 9),
('Diocesan School for Girls', 'Epsom', 'Auckland', 'Secondary', 'Private', 10),
('Kings College', 'Otahuhu', 'Auckland', 'Secondary', 'Private', 10),
('St Kentigern College', 'Pakuranga', 'Auckland', 'Secondary', 'Private', 10),
('ACG Parnell College', 'Parnell', 'Auckland', 'Secondary', 'Private', 10),
('Baradene College', 'Remuera', 'Auckland', 'Secondary', 'State Integrated', 10),
('St Peters College', 'Grafton', 'Auckland', 'Secondary', 'State Integrated', 8),
('Sacred Heart College', 'Glendowie', 'Auckland', 'Secondary', 'State Integrated', 9),
('Lynfield College', 'Lynfield', 'Auckland', 'Secondary', 'State', 7),
('Green Bay High School', 'Green Bay', 'Auckland', 'Secondary', 'State', 5),
('De La Salle College', 'Mangere East', 'Auckland', 'Secondary', 'State Integrated', 3),
('Marcellin College', 'Royal Oak', 'Auckland', 'Secondary', 'State Integrated', 6),

-- WAIKATO
('Hamilton Boys High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 8),
('Hamilton Girls High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 8),
('Hillcrest High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 8),
('Fraser High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 6),
('Fairfield College', 'Hamilton', 'Waikato', 'Secondary', 'State', 4),
('Melville High School', 'Hamilton', 'Waikato', 'Secondary', 'State', 7),
('Sacred Heart Girls College Hamilton', 'Hamilton', 'Waikato', 'Secondary', 'State Integrated', 7),
('St Johns College Hamilton', 'Hamilton', 'Waikato', 'Secondary', 'State Integrated', 6),
('Cambridge High School', 'Cambridge', 'Waikato', 'Secondary', 'State', 8),
('Te Awamutu College', 'Te Awamutu', 'Waikato', 'Secondary', 'State', 6),
('Matamata College', 'Matamata', 'Waikato', 'Secondary', 'State', 6),
('Morrinsville College', 'Morrinsville', 'Waikato', 'Secondary', 'State', 7),
('Thames High School', 'Thames', 'Waikato', 'Secondary', 'State', 5),
('Tokoroa High School', 'Tokoroa', 'Waikato', 'Secondary', 'State', 2),
('Putaruru College', 'Putaruru', 'Waikato', 'Secondary', 'State', 3),

-- BAY OF PLENTY
('Tauranga Boys College', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State', 8),
('Tauranga Girls College', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State', 7),
('Mount Maunganui College', 'Mount Maunganui', 'Bay of Plenty', 'Secondary', 'State', 8),
('Otumoetai College', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State', 9),
('Aquinas College Tauranga', 'Tauranga', 'Bay of Plenty', 'Secondary', 'State Integrated', 8),
('Bethlehem College', 'Bethlehem', 'Bay of Plenty', 'Secondary', 'Private', 9),
('Rotorua Boys High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 5),
('Rotorua Girls High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 5),
('Western Heights High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 3),
('Rotorua Lakes High School', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State', 4),
('John Paul College Rotorua', 'Rotorua', 'Bay of Plenty', 'Secondary', 'State Integrated', 6),
('Whakatane High School', 'Whakatane', 'Bay of Plenty', 'Secondary', 'State', 5),
('Trident High School', 'Whakatane', 'Bay of Plenty', 'Secondary', 'State', 4),
('Edgecumbe College', 'Edgecumbe', 'Bay of Plenty', 'Secondary', 'State', 3),
('Opotiki College', 'Opotiki', 'Bay of Plenty', 'Secondary', 'State', 2),
('Te Puke High School', 'Te Puke', 'Bay of Plenty', 'Secondary', 'State', 4),
('Katikati College', 'Katikati', 'Bay of Plenty', 'Secondary', 'State', 6),

-- GISBORNE
('Gisborne Boys High School', 'Gisborne', 'Gisborne', 'Secondary', 'State', 4),
('Gisborne Girls High School', 'Gisborne', 'Gisborne', 'Secondary', 'State', 4),
('Lytton High School', 'Gisborne', 'Gisborne', 'Secondary', 'State', 2),
('Campion College', 'Gisborne', 'Gisborne', 'Secondary', 'State Integrated', 4),

-- HAWKE'S BAY
('Napier Boys High School', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 7),
('Napier Girls High School', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 7),
('Tamatea High School', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 4),
('William Colenso College', 'Napier', 'Hawke''s Bay', 'Secondary', 'State', 5),
('Hastings Boys High School', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 6),
('Hastings Girls High School', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 6),
('Karamu High School', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 5),
('Flaxmere College', 'Hastings', 'Hawke''s Bay', 'Secondary', 'State', 1),
('Lindisfarne College', 'Hastings', 'Hawke''s Bay', 'Secondary', 'Private', 8),
('Iona College', 'Havelock North', 'Hawke''s Bay', 'Secondary', 'State Integrated', 8),
('Havelock North High School', 'Havelock North', 'Hawke''s Bay', 'Secondary', 'State', 9),
('Central Hawke''s Bay College', 'Waipukurau', 'Hawke''s Bay', 'Secondary', 'State', 5),
('Dannevirke High School', 'Dannevirke', 'Hawke''s Bay', 'Secondary', 'State', 4),

-- TARANAKI
('New Plymouth Boys High School', 'New Plymouth', 'Taranaki', 'Secondary', 'State', 8),
('New Plymouth Girls High School', 'New Plymouth', 'Taranaki', 'Secondary', 'State', 8),
('Spotswood College', 'New Plymouth', 'Taranaki', 'Secondary', 'State', 6),
('Francis Douglas Memorial College', 'New Plymouth', 'Taranaki', 'Secondary', 'State Integrated', 7),
('Sacred Heart Girls College New Plymouth', 'New Plymouth', 'Taranaki', 'Secondary', 'State Integrated', 7),
('Inglewood High School', 'Inglewood', 'Taranaki', 'Secondary', 'State', 5),
('Stratford High School', 'Stratford', 'Taranaki', 'Secondary', 'State', 6),
('Hawera High School', 'Hawera', 'Taranaki', 'Secondary', 'State', 4),
('Opunake High School', 'Opunake', 'Taranaki', 'Secondary', 'State', 4),

-- MANAWATŪ-WHANGANUI
('Palmerston North Boys High School', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 8),
('Palmerston North Girls High School', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 8),
('Freyberg High School', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 6),
('Awatapu College', 'Palmerston North', 'Manawatū-Whanganui', 'Secondary', 'State', 7),
('Longburn Adventist College', 'Longburn', 'Manawatū-Whanganui', 'Secondary', 'Private', 7),
('Feilding High School', 'Feilding', 'Manawatū-Whanganui', 'Secondary', 'State', 7),
('Whanganui High School', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'State', 5),
('Whanganui City College', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'State', 3),
('Whanganui Collegiate School', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'Private', 8),
('Cullinane College', 'Whanganui', 'Manawatū-Whanganui', 'Secondary', 'State Integrated', 5),
('Taihape Area School', 'Taihape', 'Manawatū-Whanganui', 'Area School', 'State', 3),
('Ruapehu College', 'Ohakune', 'Manawatū-Whanganui', 'Secondary', 'State', 3),

-- WELLINGTON
('Wellington College', 'Wellington', 'Wellington', 'Secondary', 'State', 10),
('Wellington Girls College', 'Wellington', 'Wellington', 'Secondary', 'State', 9),
('Wellington High School', 'Wellington', 'Wellington', 'Secondary', 'State', 7),
('Onslow College', 'Johnsonville', 'Wellington', 'Secondary', 'State', 8),
('Wellington East Girls College', 'Mount Victoria', 'Wellington', 'Secondary', 'State', 7),
