-- BATCH GRAPHRAG INDEX - Generated by batch-index-graphrag.py
-- Total resources: 2114
-- Generated: 2025-10-24 09:38:50.722067

INSERT INTO graphrag_resources (
  file_path, title, resource_type, subject, canonical_subject,
  year_level, unit, quality_score, cultural_context,
  has_te_reo, has_whakataukī, content_preview, metadata),
(
  '/public/generated-resources-alpha/lessons/scientific-method-using-traditional-māori-practices.html',
  'Scientific Method Using Traditional Māori Practices',
  'lesson',
  'Health & PE',
  'Health & PE',
  'All Years',
  NULL,
  95,
  true,
  true,
  true,
  '# Scientific Method Using Traditional Māori Practices Scientific Method Using Traditional Māori Practices fetch(''/components/navigation-standard.html'') .then(r => r.text()) .then(html => { const div = document.createElement(''div''); div.innerHTML = html; document.body.insertBefore(div.firstElementChild, document.body.firstChild); }); 🏠 Home → 📖 Lessons → Scientific Method Using Traditional Māori Practices "Ko te mātauranga te waka, ko te kaitiakitanga te ūrunga mai" Knowledge is the vessel, guard',
  '{"file_size": 18542, "has_navigation": true, "has_footer": false}'::jsonb
),
(
  '/public/generated-resources-alpha/lessons/game-development-with-cultural-themes.html',
  'Game Development with Cultural Themes',
  'lesson',
  'Health & PE',
  'Health & PE',
  'All Years',
  NULL,
  95,
  true,
  true,
  true,
  '# Game Development with Cultural Themes Game Development with Cultural Themes fetch(''/components/navigation-standard.html'') .then(r => r.text()) .then(html => { const div = document.createElement(''div''); div.innerHTML = html; document.body.insertBefore(div.firstElementChild, document.body.firstChild); }); "Kia piki ake i ngā raruraru o te kāinga" To be elevated above the ordinary — Games can carry our stories and values into the digital world Learning Objectives By the end of this unit, students',
  '{"file_size": 20147, "has_navigation": true, "has_footer": true}'::jsonb
),
(
  '/public/generated-resources-alpha/lessons/health-and-wellbeing-te-whare-tapa-whā-model.html',
  'Te Whare Tapa Whā - Health and Wellbeing',
  'lesson',
  'Health & PE',
  'Health & PE',
  'All Years',
  NULL,
  95,
  true,
  true,
  true,
  '# Health and Wellbeing: Te Whare Tapa Whā Model Te Whare Tapa Whā - Health and Wellbeing fetch(''/components/navigation-standard.html'') .then(r => r.text()) .then(html => { const div = document.createElement(''div''); div.innerHTML = html; document.body.insertBefore(div.firstElementChild, document.body.firstChild); }); 🏠 Home → 📖 Lessons → Te Whare Tapa Whā - Health and Wellbeing "Whāia te iti kahurangi ki te tūohu koe me he maunga teitei" Seek the treasures you value most dearly; if you bow your h',
  '{"file_size": 16719, "has_navigation": true, "has_footer": true}'::jsonb
),
(
  '/public/generated-resources-alpha/lessons/physics-of-traditional-māori-instruments.html',
  'Physics of Traditional Māori Instruments',
  'lesson',
  'Science',
  'Science',
  'All Years',
  NULL,
  95,
  true,
  true,
  true,
  'Physics of Traditional Māori Instruments fetch(''/components/navigation-standard.html'') .then(r => r.text()) .then(html => { const div = document.createElement(''div''); div.innerHTML = html; document.body.insertBefore(div.firstElementChild, document.body.firstChild); }); 🏠 Home → 📖 Lessons → Physics of Traditional Māori Instruments "Te manu e kai ana i te miro, nōna te ngahere. Te manu e kai ana i te mātauranga, nōna te ao" The bird that eats the miro berry owns the forest; the bird that partakes ',
  '{"file_size": 13325, "has_navigation": true, "has_footer": false}'::jsonb
)
ON CONFLICT (file_path) DO UPDATE SET
  title = EXCLUDED.title,
  resource_type = EXCLUDED.resource_type
ON CONFLICT (file_path) DO UPDATE SET
  title = EXCLUDED.title,
  resource_type = EXCLUDED.resource_type,
  quality_score = EXCLUDED.quality_score,
  cultural_context = EXCLUDED.cultural_context,
  updated_at = NOW();
