-- BATCH GRAPHRAG INDEX - Generated by batch-index-graphrag.py
-- Total resources: 2114
-- Generated: 2025-10-24 09:38:50.722067

INSERT INTO graphrag_resources (
  file_path, title, resource_type, subject, canonical_subject,
  year_level, unit, quality_score, cultural_context,  has_te_reo, has_whakataukī, content_preview, metadata
) VALUES
(
  '/public/admin-youtube-library.html',
  'YouTube Library Administration | Te Kete Ako',
  'lesson',
  'Mathematics',
  'Mathematics',
  'All Years',
  NULL,
  90,
  true,
  true,
  false,
  'YouTube Library Administration | Te Kete Ako | Te Kete Ako fetch(''/components/navigation-standard.html'') .then(r => r.text()) .then(html => document.getElementById(''nav-container'').innerHTML = html); YouTube Library Administration | Te Kete Ako Mathematics Subject 8 Year Level ⭐ 100 Quality 🌿 Culturally Integrated 🗣️ Te Reo Māori 📖 Resource Content 📋 Content Preview YouTube Library Administration | Te Kete Ako 📊 Resource Information Resource Type: other Quality Score: 100/100 Cultural Integratio',
  '{"file_size": 6036, "has_navigation": false, "has_footer": true}'::jsonb
),
(
  '/public/cultural-connection-pathways.html',
  'Cultural Connection Pathways',
  'lesson',
  'Health & PE',
  'Health & PE',
  'All Years',
  NULL,
  91,
  true,
  true,
  false,
  'Cultural Connection Pathways | Te Kete Ako fetch(''/components/navigation-standard.html'') .then(r => r.text()) .then(html => document.getElementById(''nav-container'').innerHTML = html); 🧠 POWERED BY GRAPHRAG INTELLIGENCE 🌿 Cultural Connection Pathways Discover how mātauranga Māori weaves through all subject areas 240,973 Knowledge Connections 687 Resources Analyzed 84% Cultural Integration What Are Cultural Connection Pathways? Mātauranga Māori doesn''t exist in silos - it''s a holistic worldview th',
  '{"file_size": 18987, "has_navigation": false, "has_footer": false}'::jsonb
),
(
  '/public/teacher-insights-dashboard.html',
  'Teacher Insights - Te Kete Ako',
  'lesson',
  'Te Ao Māori',
  'Te Ao Māori',
  'All Years',
  NULL,
  95,
  true,
  true,
  true,
