
-- Generated Resources Alpha - Bulk Insert to GraphRAG
-- Date: October 16, 2025
-- Count: 47 resources

INSERT INTO resources (title, description, path, type, subject, level, tags, author, featured) VALUES
(
    'Algebraic Thinking in Traditional Māori Games | Te Kete Ako',
    'Explore algebraic thinking through traditional Māori games - integrating mātauranga Māori with mathematical concepts',
    '/public/generated-resources-alpha/handouts/algebraic-thinking-in-traditional-māori-games.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration","traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Biotechnology Ethics Through Māori Worldview',
    'Exploring the intersection of science, ethics, and Te Ao Māori',
    '/public/generated-resources-alpha/handouts/biotechnology-ethics-through-māori-worldview.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Leadership Development Through Cultural Values',
    'Exploring Māori Leadership Principles for Young People',
    '/public/generated-resources-alpha/handouts/leadership-development-through-cultural-values.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Visual Arts Analysis with Māori Aesthetic Principles',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/visual-arts-analysis-with-cultural-context.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Cultural Safety Checklists for Classroom Discussions - Te Kete Ako',
    'Subject: social-sciences | Year Level: Years 7-13',
    '/public/generated-resources-alpha/handouts/cultural-safety-checklists-for-classroom-discussions.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Workplace Readiness with Cultural Competency',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/workplace-readiness-with-cultural-competency.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Digital Equity & Accessibility - Mobile Learning Guide',
    'Navigating Digital Equity and Accessibility in Aotearoa',
    '/public/generated-resources-alpha/handouts/chromebook-optimized-mobile-learning-guide.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Financial Literacy with Māori Economic Principles - Te Kete Ako',
    'Subject: social-sciences | Year Level: Years 11-13',
    '/public/generated-resources-alpha/handouts/financial-literacy-with-māori-economic-principles.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Geometric Patterns in Māori Art and Architecture',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/geometric-patterns-in-māori-art-and-architecture.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Data Visualization of Cultural Demographics',
    'Year Levels: 11-13 | Subject: Mathematics - Statistics',
    '/public/generated-resources-alpha/handouts/data-visualization-of-cultural-demographics.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Statistical Analysis of Treaty Settlement Data',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/statistical-analysis-of-treaty-settlement-data.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Coding Projects Inspired by Māori Patterns',
    'Connecting Digital Technology with Traditional Māori Art Forms',
    '/public/generated-resources-alpha/handouts/coding-projects-inspired-by-māori-patterns.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Sustainable Energy Solutions from Traditional Knowledge',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/sustainable-energy-solutions-from-traditional-knowledge.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Year 9 Starter Pack: Essential Skills for High School Success - Te Kete Ako',
    'Subject: cross-curricular | Year Level: Year 9',
    '/public/generated-resources-alpha/handouts/year-9-starter-pack-essential-skills-for-high-school-success.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'NCEA Level 1 Literacy & Numeracy Must-Knows - Te Kete Ako',
    'Subject: cross-curricular | Year Level: Year 11',
    '/public/generated-resources-alpha/handouts/ncea-level-1-literacy-and-numeracy-must-knows.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"ncea"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Probability and Chance in Māori Games',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/probability-and-chance-in-māori-games.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Public Speaking with Cultural Confidence',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/public-speaking-with-cultural-confidence.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Food Security Through Traditional Knowledge Systems',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/food-security-through-traditional-knowledge-systems.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"traditional-knowledge","stem"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Mathematical Modeling of Ecological Systems',
    'Integrating Mātauranga Māori and Mathematical Thinking',
    '/public/generated-resources-alpha/handouts/mathematical-modeling-of-ecological-systems.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"stem"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Calculus Applications in Environmental Modeling',
    'Integrating Traditional Ecological Knowledge with Mathematical Analysis',
    '/public/generated-resources-alpha/handouts/calculus-applications-in-environmental-modeling.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Chemistry of Traditional Māori Medicine | Te Kete Ako',
    'Rongoā Māori refers to traditional Māori healing practices that include the use of medicinal plants (rongoā rākau), spiritual healing, and physical therapies. This resource focuses on the scientific a',
    '/public/generated-resources-alpha/handouts/chemistry-of-traditional-māori-medicine.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration","traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Information Literacy in the Digital Age',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/information-literacy-in-the-digital-age.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Te Reo Maths Glossary (Key Terms in Māori & English) - Te Kete Ako',
    'Subject: mathematics | Year Level: Years 7-13',
    '/public/generated-resources-alpha/handouts/te-reo-maths-glossary-key-terms-in-māori-and-english.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Global Citizenship with Tangata Whenua Perspective',
    'Exploring Indigenous worldviews in the context of global citizenship',
    '/public/generated-resources-alpha/handouts/global-citizenship-with-tangata-whenua-perspective.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Social Media and Cultural Identity',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/handouts/social-media-and-cultural-identity.html',
    'handout',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'AI Ethics Through Māori Data Sovereignty',
    'He tapu te raraunga | Data is sacred',
    '/public/generated-resources-alpha/lessons/ai-ethics-through-māori-data-sovereignty.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Media Literacy: Analyzing Māori Representation',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/lessons/media-literacy-analyzing-māori-representation.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Statistical Analysis of Sports Performance',
    'Exploring data through Māori and contemporary sports',
    '/public/generated-resources-alpha/lessons/statistical-analysis-of-sports-performance.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Career Pathways in STEM for Māori Students',
    'Exploring culturally connected STEM opportunities for Years 11-13',
    '/public/generated-resources-alpha/lessons/career-pathways-in-stem-for-māori-students.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration","stem"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Poetry Analysis Through Māori Literary Traditions',
    'Exploring traditional and contemporary Māori poetry',
    '/public/generated-resources-alpha/lessons/poetry-analysis-through-māori-literary-traditions.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'AI Ethics Through Māori Data Sovereignty | Te Kete Ako',
    '{LESSON_SUBTITLE}',
    '/public/generated-resources-alpha/lessons/ai-ethics-through-māori-data-sovereignty-FIXED.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Narrative Writing Using Māori Story Structures',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/lessons/narrative-writing-using-māori-story-structures.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Research Skills: Traditional and Digital Sources',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/lessons/research-skills-using-traditional-and-digital-sources.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Creative Writing Inspired by Whakataukī',
    'Traditional wisdom in modern expression',
    '/public/generated-resources-alpha/lessons/creative-writing-inspired-by-whakataukī.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Debate Skills with Māori Oratory Traditions',
    'Connecting Whaikōrero with Contemporary Debate',
    '/public/generated-resources-alpha/lessons/debate-skills-with-māori-oratory-traditions.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Critical Analysis of Historical Documents | Te Kete Ako',
    'Examining Colonial and Māori Perspectives in Aotearoa New Zealand History',
    '/public/generated-resources-alpha/lessons/critical-analysis-of-historical-documents.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Traditional Navigation & Modern GPS Integration - Te Kete Ako',
    'Subject: science | Year Level: Years 9-11',
    '/public/generated-resources-alpha/lessons/traditional-navigation-and-modern-gps-integration.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Genetics and Whakapapa',
    'This lesson explores the connections between Western scientific understandings of genetics and Māori concepts of whakapapa (genealogy). We acknowledge that these are different but complementary knowle',
    '/public/generated-resources-alpha/lessons/genetics-and-whakapapa-scientific-and-cultural-perspectives.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Renewable Energy and Māori Innovation',
    '"Whāia te iti kahurangi"',
    '/public/generated-resources-alpha/lessons/renewable-energy-and-māori-innovation.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Creative Problem Solving with Design Thinking',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/lessons/creative-problem-solving-with-design-thinking.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Climate Change Through Te Taiao Māori Lens - Te Kete Ako',
    'Subject: science | Year Level: Years 10-12',
    '/public/generated-resources-alpha/lessons/climate-change-through-te-taiao-māori-lens.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Digital Storytelling with Pūrākau Framework',
    'Year Levels: Years 8-10 | Subject: English',
    '/public/generated-resources-alpha/lessons/digital-storytelling-with-pūrākau-framework.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Argumentative Writing on Contemporary Māori Issues',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/lessons/argumentative-writing-on-contemporary-māori-issues.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Scientific Method Using Traditional Māori Practices',
    'This lesson validates mātauranga Māori (Māori knowledge) as a legitimate scientific approach while maintaining respect for its sacred aspects. We''ll explore how traditional Māori observation and exper',
    '/public/generated-resources-alpha/lessons/scientific-method-using-traditional-māori-practices.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration","traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Game Development with Cultural Themes',
    'Te Kete Ako - Award-winning educational platform integrating mātauranga Māori with contemporary learning',
    '/public/generated-resources-alpha/lessons/game-development-with-cultural-themes.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Te Whare Tapa Whā - Health and Wellbeing',
    'Exploring Holistic Health and Wellbeing',
    '/public/generated-resources-alpha/lessons/health-and-wellbeing-te-whare-tapa-whā-model.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{},
    'Generated Resources Alpha Oct 2025',
    true
),
(
    'Physics of Traditional Māori Instruments',
    'Exploring sound science through ngā taonga pūoro',
    '/public/generated-resources-alpha/lessons/physics-of-traditional-māori-instruments.html',
    'lesson',
    'Cross-curricular',
    'Y9-13',
    ARRAY{"cultural-integration","traditional-knowledge"},
    'Generated Resources Alpha Oct 2025',
    true
)
ON CONFLICT (path) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = now();
